maintainer       "atmos.org"
maintainer_email "atmos@atmos.org"
license          "MIT"
description      "Installs/Configures ruby"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "0.1"
provides         "ruby::irbrc"
provides         "ruby::rails"
provides         "ruby::bundler"
provides         "ruby::sinatra"
